FROM rust:1.39-buster

RUN apt-get update && apt-get install -y libtool \
	automake \
	pkg-config \
	cmake \
	ragel \
	jq \
	patchelf \	
	gcc-arm-linux-gnueabihf \
	g++-arm-linux-gnueabihf \
	libdjvulibre-dev \
	libharfbuzz-dev \
	libcairo2-dev \
	libstdc++6 \
	libsdl2-dev \
 	# start mupdf dependencies
	libjbig2dec0-dev \
	patch
 	# end mupdf dependencies

WORKDIR /tmp

# Build modified mupdf and wrapper
COPY contrib/ /tmp/contrib/
COPY thirdparty/ /tmp/thirdparty/
COPY src/wrapper/ /tmp/wrapper/
RUN wget -qO - "https://mupdf.com/downloads/archive/mupdf-1.16.0-source.tar.gz" | tar -xz --strip-components 1 -C "/tmp/thirdparty/mupdf/" \
	&& cp /tmp/contrib/linux/mupdf/* /tmp/thirdparty/mupdf/ \
	&& cd /tmp/thirdparty/mupdf/ && (patch -p1 < linux.patch) && ./build-linux.sh && cp /tmp/thirdparty/mupdf/build/release/libmupdf.so /usr/lib/ \
	&& cd /tmp/wrapper/ && CFLAGS="-I /tmp/thirdparty/mupdf/include" ./build.sh && cp /tmp/wrapper/libmupdfwrapper.so /usr/lib/

# Build plato
WORKDIR /plato

ADD . /plato
CMD ["bash", "-c", "cargo test && cargo build --all-features"]
