#! /usr/bin/env python2
# -*- coding: utf-8 -*-

import json
import fontforge

font = fontforge.font()
font.fontname = "Icons"
font.familyname = font.fontname
font.em = 2048
font.ascent = 1024
font.descent = 1024
index = {}

with open("glyphs.json") as f:
    index = json.load(f)

for c, path in index.items():
    print("{} {}".format(c, path))
    glyph = font.createChar(ord(c))
    glyph.importOutlines(path)

font.generate("icons.ttf")
