name: armhf

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: (armhf) build image
      run: docker build . -f Dockerfile -t plato:armhf
    - name: (armhf) build plato
      run: docker run --rm plato:armhf
