name: dev

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: (dev) build image
      run: docker build . -f Dockerfile.dev -t plato:dev
    - name: (dev) run tests and build all features
      run: docker run --rm plato:dev
